const googleTranslateLanguages = {
    "af": { "af": "Afrikaans" },
    "sq": { "sq": "Shqip" },
    "am": { "am": "አማርኛ" },
    "ar": { "ar": "العربية" },
    "hy": { "hy": "Հայերեն" },
    "az": { "az": "Azərbaycanca" },
    "eu": { "eu": "Euskara" },
    "be": { "be": "Беларуская" },
    "bn": { "bn": "বাংলা" },
    "bs": { "bs": "Bosanski" },
    "bg": { "bg": "Български" },
    "my": { "my": "မြန်မာစာ" },
    "ca": { "ca": "Català" },
    "ceb": { "ceb": "Cebuano" },
    "zh-CN": { "zh-CN": "中文(简体)" },
    "zh-TW": { "zh-TW": "中文(繁體)" },
    "co": { "co": "Corsu" },
    "hr": { "hr": "Hrvatski" },
    "cs": { "cs": "Čeština" },
    "da": { "da": "Dansk" },
    "nl": { "nl": "Nederlands" },
    "en": { "en": "English" },
    "eo": { "eo": "Esperanto" },
    "et": { "et": "Eesti" },
    "fi": { "fi": "Suomi" },
    "fr": { "fr": "Français" },
    "fy": { "fy": "Frysk" },
    "gl": { "gl": "Galego" },
    "ka": { "ka": "ქართული" },
    "de": { "de": "Deutsch" },
    "el": { "el": "Ελληνικά" },
    "gu": { "gu": "ગુજરાતી" },
    "ht": { "ht": "Kreyòl Ayisyen" },
    "ha": { "ha": "Hausa" },
    "haw": { "haw": "'Ōlelo Hawai'i" },
    "he": { "he": "עברית" },
    "hi": { "hi": "हिन्दी" },
    "hmn": { "hmn": "Hmoob" },
    "hu": { "hu": "Magyar" },
    "is": { "is": "Íslenska" },
    "ig": { "ig": "Igbo" },
    "id": { "id": "Bahasa Indonesia" },
    "ga": { "ga": "Gaeilge" },
    "it": { "it": "Italiano" },
    "ja": { "ja": "日本語" },
    "jv": { "jv": "Basa Jawa" },
    "kn": { "kn": "ಕನ್ನಡ" },
    "kk": { "kk": "Қазақ тілі" },
    "km": { "km": "ភាសាខ្មែរ" },
    "rw": { "rw": "Kinyarwanda" },
    "ko": { "ko": "한국어" },
    "ku": { "ku": "Kurdî" },
    "ky": { "ky": "Кыргызча" },
    "lo": { "lo": "ລາວ" },
    "la": { "la": "Latina" },
    "lv": { "lv": "Latviešu" },
    "lt": { "lt": "Lietuvių" },
    "lb": { "lb": "Lëtzebuergesch" },
    "mk": { "mk": "Македонски" },
    "mg": { "mg": "Malagasy" },
    "ms": { "ms": "Bahasa Melayu" },
    "ml": { "ml": "മലയാളം" },
    "mt": { "mt": "Malti" },
    "mi": { "mi": "Māori" },
    "mr": { "mr": "मराठी" },
    "mn": { "mn": "Монгол" },
    "ne": { "ne": "नेपाली" },
    "no": { "no": "Norsk" },
    "ny": { "ny": "Chichewa" },
    "or": { "or": "ଓଡ଼ିଆ" },
    "ps": { "ps": "پښتو" },
    "fa": { "fa": "فارسی" },
    "pl": { "pl": "Polski" },
    "pt": { "pt": "Português" },
    "pa": { "pa": "ਪੰਜਾਬੀ" },
    "ro": { "ro": "Română" },
    "ru": { "ru": "Русский" },
    "sm": { "sm": "Samoan" },
    "gd": { "gd": "Gàidhlig" },
    "sr": { "sr": "Српски" },
    "st": { "st": "Sesotho" },
    "sn": { "sn": "Shona" },
    "sd": { "sd": "سنڌي" },
    "si": { "si": "සිංහල" },
    "sk": { "sk": "Slovenčina" },
    "sl": { "sl": "Slovenščina" },
    "so": { "so": "Soomaali" },
    "es": { "es": "Español" },
    "su": { "su": "Basa Sunda" },
    "sw": { "sw": "Kiswahili" },
    "sv": { "sv": "Svenska" },
    "tl": { "tl": "Tagalog" },
    "tg": { "tg": "Тоҷикӣ" },
    "ta": { "ta": "தமிழ்" },
    "tt": { "tt": "Татар" },
    "te": { "te": "తెలుగు" },
    "th": { "th": "ไทย" },
    "tr": { "tr": "Türkçe" },
    "tk": { "tk": "Türkmen" },
    "uk": { "uk": "Українська" },
    "ur": { "ur": "اردو" },
    "ug": { "ug": "ئۇيغۇرچە" },
    "uz": { "uz": "O'zbek" },
    "vi": { "vi": "Tiếng Việt" },
    "cy": { "cy": "Cymraeg" },
    "xh": { "xh": "isiXhosa" },
    "yi": { "yi": "ייִדיש" },
    "yo": { "yo": "Yorùbá" },
    "zu": { "zu": "isiZulu" },
    "ak": { "ak": "Akan" },
    "an": { "an": "Aragonés" },
    "as": { "as": "অসমীয়া" },
    "ay": { "ay": "Aymar" },
    "ba": { "ba": "Башҡорт" },
    "bh": { "bh": "भोजपुरी" },
    "bi": { "bi": "Bislama" },
    "bm": { "bm": "Bamanankan" },
    "bo": { "bo": "བོད་སྐད་" },
    "br": { "br": "Brezhoneg" },
    "bug": { "bug": "Basa Ugi" },
    "cb": { "cb": "Chavacano" },
    "chr": { "chr": "ᏣᎳᎩ" },
    "chy": { "chy": "Tsėhesenėstsestotse" },
    "cr": { "cr": "Nēhiyawēwin" },
    "dv": { "dv": "ދިވެހި" },
    "dz": { "dz": "རྫོང་ཁ" },
    "ee": { "ee": "Eʋegbe" },
    "fon": { "fon": "Fɔngbè" },
    "gn": { "gn": "Avañe'ẽ" },
    "gv": { "gv": "Gaelg" },
    "ho": { "ho": "Hiri Motu" },
    "ie": { "ie": "Interlingue" },
    "ik": { "ik": "Iñupiaq" },
    "ilo": { "ilo": "Ilokano" },
    "inh": { "inh": "ГӀалгӀай" },
    "iu": { "iu": "ᐃᓄᒃᑎᑐᑦ" },
    "kab": { "kab": "Taqbaylit" },
    "kbd": { "kbd": "Адыгэбзэ" },
    "kha": { "kha": "Khasi" },
    "kj": { "kj": "Kuanyama" },
    "kl": { "kl": "Kalaallisut" },
    "kr": { "kr": "Kanuri" },
    "ks": { "ks": "कश्मीरी" },
    "kum": { "kum": "Къумукъ" },
    "kv": { "kv": "Коми" },
    "kw": { "kw": "Kernewek" },
    "lez": { "lez": "Лезги" },
    "lg": { "lg": "Luganda" },
    "li": { "li": "Limburgs" },
    "ln": { "ln": "Lingála" },
    "mdf": { "mdf": "Мокшень" },
    "mh": { "mh": "Kajin M̧ajeļ" },
    "mnc": { "mnc": "ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ" },
    "mos": { "mos": "Mòoré" },
    "na": { "na": "Dorerin Naoero" },
    "ng": { "ng": "Oshiwambo" },
    "nv": { "nv": "Diné bizaad" },
    "olo": { "olo": "Livvi" },
    "os": { "os": "Ирон" },
    "ota": { "ota": "لسان عثمانى" },
    "pag": { "pag": "Pangasinan" },
    "pam": { "pam": "Kapampangan" },
    "pap": { "pap": "Papiamentu" },
    "pau": { "pau": "Tekoi er a Belau" },
    "qu": { "qu": "Runasimi" },
    "quc": { "quc": "K'iche'" },
    "rm": { "rm": "Rumantsch" },
    "rn": { "rn": "Ikirundi" },
    "rup": { "rup": "Armãneashce" },
    "sah": { "sah": "Саха тыла" },
    "sc": { "sc": "Sardu" },
    "scn": { "scn": "Sicilianu" },
    "sco": { "sco": "Scots" },
    "shn": { "shn": "ၽႃႇသႃႇတႆး" },
    "sid": { "sid": "Sidaamu Afoo" },
    "srn": { "srn": "Sranan Tongo" },
    "ss": { "ss": "SiSwati" },
    "sux": { "sux": "𒅴𒂠" },
    "szl": { "szl": "Ślōnskŏ gŏdka" },
    "tet": { "tet": "Tetun" },
    "tig": { "tig": "ትግረ" },
    "tiv": { "tiv": "Tiv" },
    "tkl": { "tkl": "Tokelau" },
    "tli": { "tli": "Lingít" },
    "tpi": { "tpi": "Tok Pisin" },
    "ts": { "ts": "Xitsonga" },
    "tum": { "tum": "ChiTumbuka" },
    "tw": { "tw": "Twi" },
    "ty": { "ty": "Reo Tahiti" },
    "udm": { "udm": "Удмурт" },
    "ve": { "ve": "Tshivenḓa" },
    "vo": { "vo": "Volapük" },
    "wa": { "wa": "Walon" },
    "war": { "war": "Winaray" },
    "xal": { "xal": "Хальмг" },
    "yao": { "yao": "Chiyao" },
    "zap": { "zap": "Diidxazá" },
    "zbl": { "zbl": "Blissymbols" },
    "zen": { "zen": "Tuḍḍungiyya" },
    "zgh": { "zgh": "ⵜⴰⵎⴰⵣⵉⵖⵜ" },
    "zun": { "zun": "Shiwi'ma" }
};


function extractLanguages(text) {
    if (!text) return null;
    const cleanText = text.replace(/^\./, "").trim(); // Boshidagi nuqtani olib tashlaymiz
    let [to, from] = cleanText.split(" ");
    if (!googleTranslateLanguages[to]) return null
    from = from || 'auto'; // Agar from bo'sh bo'lsa, 'auto'ga o'zgartiramiz
    return { to, from };
}

module.exports = { googleTranslateLanguages, extractLanguages };